services:
  mongo:
    image: mongo:6
    container_name: test-crud-front-back-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/brandmanager
      - JWT_SECRET=supersecretkey
      - PORT=5000
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    restart: always
    environment:
      - VITE_API_URL=http://backend:5050
    ports:
      - 5173:5173
    depends_on:
      - backend

volumes:
  mongo-data:
